---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demochat_board
  labels:
    service: demochat_board
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        forceRedeployUniqId: "{{CF_REVISION}}"
      labels:
        service: demochat_board
    spec:
      containers:
      - image: verchol/demochat_board:{{CF_BRANCH}}
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
