---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
data:
  test: |
    aaaa
    bbbb
    cccc
    dddd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    service: app
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        forceRedeployUniqId: "{{CF_REVISION}}"
      labels:
        service: app
    spec:
      containers:
      - image: containers101/demochat:{{CF_BRANCH}}
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP

