---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    service: app
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        forceRedeployUniqId: "{{CF_REVISION}}"
      labels:
        service: app
    spec:
      containers:
      - image: chloecodesthings/demochat:{{CF_BRANCH}}
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP

