apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: "{{.Values.imagePullSecret}}"
      {{- end }}    
      containers:
      - name: {{.Release.Name}}
        image: "{{ .Values.repositoryRaw }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: MONGO_HELM
          value: "{{.Release.Name}}-mongo"
#        livenessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#        readinessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#        resources:
